server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkatanukala/spring-cloud-config-store-codelab.git
          search-paths:
           - '*service'



